namespace:
  name: prod

image:
  repository:
    nginx
  tag: 1.17.0
  pull:
    policy: IfNotPresent

resources:
  cpu: 70m
  memory: 256Mi
service:
  type: ClusterIP
  port: 80
configmap:
  data: "version: 1.17.0"

replicaCount: 2