apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-ssl-cert":"arn:aws:acm:us-east-2:882275506731:certificate/675d22d7-d557-4831-a574-47ce179e7df7","service.beta.kubernetes.io/aws-load-balancer-ssl-ports":"https"},"creationTimestamp":"2022-07-09T18:46:25Z","finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/name":"argocd-server","app.kubernetes.io/part-of":"argocd"},"name":"argocd-server","namespace":"argocd","resourceVersion":"898666","uid":"0a20d8ad-53e2-4086-be58-3e0cc24c096f"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"172.20.12.8","clusterIPs":["172.20.12.8"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"http","nodePort":31127,"port":80,"protocol":"TCP","targetPort":8080},{"name":"https","nodePort":30371,"port":443,"protocol":"TCP","targetPort":8080}],"selector":{"app.kubernetes.io/name":"argocd-server"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"hostname":"a0a20d8ad53e24086be583e0cc24c096-2042626204.us-east-2.elb.amazonaws.com"}]}}}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:882275506731:certificate/675d22d7-d557-4831-a574-47ce179e7df7
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  creationTimestamp: "2022-07-09T18:46:25Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
  resourceVersion: "898799"
  uid: 0a20d8ad-53e2-4086-be58-3e0cc24c096f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.12.8
  clusterIPs:
  - 172.20.12.8
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31127
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30371
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a0a20d8ad53e24086be583e0cc24c096-2042626204.us-east-2.elb.amazonaws.com
